name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install basedpyright ruff ty

    - name: Run ty check
      run: ty check crash_tournament/

    - name: Run ruff check
      run: ruff check crash_tournament/

    - name: Run basedpyright type checking
      run: basedpyright crash_tournament/

    - name: Run pytest
      run: pytest