name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install basedpyright ruff ty

    - name: Run ty check
      run: ty check

    - name: Run ruff check
      run: ruff check

    - name: Run basedpyright type checking
      run: |
        output=$(basedpyright 2>&1) || true
        echo "$output"
        if echo "$output" | grep -qE '^[1-9][0-9]* errors'; then
          echo "Type checking failed with errors"
          exit 1
        fi
        echo "Type checking passed (warnings are allowed)"

    - name: Run pytest
      run: pytest